DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `captenchuthaucocgtrinhCung1tpho`()
BEGIN
	SELECT DISTINCT C1.TEN_THAU, C2.TEN_THAU
	FROM CGTRINH C1 JOIN CGTRINH C2 ON C1.TINH_THANH = C2.TINH_THANH 
	WHERE C1.TEN_THAU < C2.TEN_THAU;
END//
DELIMITER ;


DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `captencongnhanLamvien2cgtrinh`()
BEGIN
	SELECT T1.HOTEN_CN, T2.HOTEN_CN
	FROM THAMGIA T1 JOIN THAMGIA T2 ON T1.STT_CTR = T2.STT_CTR 
	WHERE T1.HOTEN_CN > T2.HOTEN_CN 
	GROUP BY T1.HOTEN_CN, T2.HOTEN_CN HAVING COUNT(*)>1;
END//
DELIMITER ;


DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `cgnhanThamgiatatcactrinh`()
BEGIN
	SELECT HOTEN_CN, COUNT(*) SỐ_CT 
	FROM THAMGIA 
	GROUP BY HOTEN_CN;
END//
DELIMITER ;


DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `chuthauTrungkinhphiit`()
BEGIN
	SELECT CT.TEN_THAU, DCHI_THAU 
	FROM CGTRINH CT JOIN CHUTHAU C ON CT.TEN_THAU = C.TEN_THAU
	WHERE KINH_PHI = (SELECT MIN(KINH_PHI)FROM CGTRINH);
END//
DELIMITER ;


DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `ctrinhcoCNthamgianhieunhat`()
BEGIN
	SELECT TEN_CTR, DIACHI_CTR
	FROM CAU27 JOIN CGTRINH C ON CAU27.STT_CTR = C.STT_CTR 
	WHERE SO_CN = (SELECT MAX(SO_CN) FROM CAU27);
END//
DELIMITER ;


DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `hotenchuyenmonCNdoktrsu_input_thietke`(IN KTS varchar(50))
BEGIN
	SELECT T.HOTEN_CN, CH_MON
	FROM THAMGIA T JOIN CGTRINH CT ON T.STT_CTR = CT.STT_CTR
			       JOIN CONGNHAN C ON C.HOTEN_CN = T.HOTEN_CN 
                   JOIN THIETKE K ON K.STT_CTR = CT.STT_CTR 
WHERE HOTEN_KTS = KTS;
END//
DELIMITER ;


DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `kinhphiTBtheotungtpho`()
BEGIN
	SELECT TINH_THANH, AVG(KINH_PHI)
	FROM CGTRINH 
	GROUP BY TINH_THANH;
END//
DELIMITER ;


DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `ktrucsuThulaothap`()
BEGIN
	SELECT DISTINCT HOTEN_KTS 
	FROM THIETKE 
	WHERE THU_LAO < (SELECT AVG(THU_LAO) FROM THIETKE); 
END//
DELIMITER ;


DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `ktscoTienthulaohon25tr`()
BEGIN
	SELECT HOTEN_KTS, SUM(THU_LAO) TỔNG 
	FROM THIETKE 
	GROUP BY HOTEN_KTS HAVING SUM(THU_LAO) > 25;
END//
DELIMITER ;


DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `sluongKTSthulaohon25tr`()
BEGIN
	SELECT COUNT(*)
	FROM (SELECT HOTEN_KTS, SUM(THU_LAO) TỔNG
	FROM THIETKE 
	GROUP BY HOTEN_KTS HAVING SUM(THU_LAO) > 25) C24;
END//
DELIMITER ;


DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `songaylamcacCNlonhonCNINPUT`(IN CN varchar(50))
BEGIN
	SELECT HOTEN_CN, SUM(SO_NGAY)
	FROM THAMGIA 
	GROUP BY HOTEN_CN HAVING SUM(SO_NGAY) > (SELECT SUM(SO_NGAY) FROM THAMGIA WHERE HOTEN_CN = CN);
END//
DELIMITER ;


DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `tongCNthamgiamoictr`()
BEGIN
	SELECT STT_CTR, COUNT(*) SO_CN
	FROM THAMGIA GROUP BY STT_CTR;
END//
DELIMITER ;


DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `tongkinhphicgtrinhTheochuthau`()
BEGIN
	SELECT TEN_THAU, SUM(KINH_PHI) TỔNG 
	FROM CGTRINH 
	GROUP BY TEN_THAU;
END//
DELIMITER ;


DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `tongsoctrMoiKTSthietke`()
BEGIN
	SELECT HOTEN_KTS, COUNT(*) SỐ_CTR
	FROM THIETKE 
	GROUP BY HOTEN_KTS;
END//
DELIMITER ;